### ISSUE TITLE
I put this in the popup but the truth is I'm a bit lost

### ISSUE THREAD

**Issue by FJRG2007** [davestewart/extension-bus#10]
![image](https://github.com/davestewart/extension-bus/assets/79384376/88b9971f-561e-4c76-9ed3-86376d94686b)
![image](https://github.com/davestewart/extension-bus/assets/79384376/a9aef79a-e3d0-4223-be7d-c51ddd538796)

**Comment by davestewart** [comment]
So, as mentioned in the thread, you need to set up a bus in each of the processes you want to connect.

## Assumptions

I am assuming that you are using:

- a popup
- a content script

In each process you will need to:

- setup a bus
- optionally add handlers

## Setup

So, in the popup, try the following:

```ts
// popup.ts
import { makeBus } from '@davestewart/extension-bus' // or from 'bus' if you used the shorthand

const bus = new Bus('popup')
```

In the content script:

```ts
// content.ts
import { makeBus } from '@davestewart/extension-bus' // or from 'bus' if you used the shorthand

const bus = new Bus('search', {
  handlers: {
    showList (params) {
      console.log('Showing the list!', params)
    }
  }
})
```

## Usage

Now you are set up, you can call one from the other:

```ts
// popup.ts

// ...previous code

function onClick () {
  bus.call('search:showList', { a: 1 })
}
```

That's really the basics of it.

You will need to read the docs to understand more.

They are pretty easy to follow.

If you want to see working code, you can clone the repo, run the build script then install the built extension, modify the code, etc, etc

**Comment by FJRG2007** [comment]
![image](https://github.com/davestewart/extension-bus/assets/79384376/86e23eed-05e1-4507-8eb6-81607cdbf354)
Which of the 2 should I use to create the bus?

**Comment by davestewart** [comment]
Use `makeBus()`

**Comment by FJRG2007** [comment]
![image](https://github.com/davestewart/extension-bus/assets/79384376/f1c97740-bd0a-404a-9906-05e16c902dbd)
![image](https://github.com/davestewart/extension-bus/assets/79384376/c3d19d64-7f10-4f0e-bf03-c5826a8d877f)

This is the unlisted page and I want to receive it but I get an error with "new".

**Comment by FJRG2007** [comment]
![image](https://github.com/davestewart/extension-bus/assets/79384376/cc8cb24d-e64c-4fc3-9a78-66e85b4c82de)

**Comment by davestewart** [comment]
Remove the `new`; it is just `const bus = makeBus(name, options)`

**Comment by FJRG2007** [comment]
```tsx
 const bus = makeBus("popup", {
 // Optionally target a specific process.
      target: "background",
      // Handle incoming requests.
      handlers: {
          foo(value, sender) { },
          bar(value, { tab }) { },
      },
       // Allow external connection.
       external: true,
  })

let tabs = await browser.tabs.query({ url: browser.runtime.getURL('/autoSearchTasks.html') });
if (tabs.length > 0) for (let tab of tabs) { if (tab.id) await browser.tabs.remove(tab.id); };
const autoSearchTasks = await browser.tabs.create({ url: browser.runtime.getURL('/autoSearchTasks.html') });
bus.call('search:showList', { status: true, type: "showListOnNewPage", params: { elements: listElements } });
 ```
 
 I put that in the popup, and the following in the unlisted page but it doesn't show me anything by console
 
 ```tsx
 const bus = makeBus("search", {
            handlers: {
                showList(params) {
                    console.log('Showing the list!', params);
                }
            }
        });
 ```

**Comment by davestewart** [comment]
OK. I see what the confusion is.

You should not be targeting `background`.

All you need in the popup is:

```ts
// make bus
const bus = makeBus("popup")

// kill old tabs
let tabs = await browser.tabs.query({ url: browser.runtime.getURL('/autoSearchTasks.html') });
if (tabs.length > 0) for (let tab of tabs) { if (tab.id) await browser.tabs.remove(tab.id); };

// create new tab
const autoSearchTasks = await browser.tabs.create({ url: browser.runtime.getURL('/autoSearchTasks.html') });

// send message to tab
bus.call('search:showList', { status: true, type: "showListOnNewPage", params: { elements: listElements } });
```

You do not need the bus `target` property, as that will override the `name:` part of the `call()`.

All you need on the extension page `/autoSearchTasks.html` is:

```ts
const bus = makeBus('search', {
    handlers: {
        showList(params) {
            console.log('Showing the list!', params)
        },
    },
})
```

On your website is say you are an experienced developer.

This is pretty basic stuff, especially when you have read the docs, which you could have done in the time it has taken me to help you.

FWIW the principle of the package is to set up named buses in each process and call from one to the other, by name.

Perhaps I can make that more clear in the docs?

**Comment by FJRG2007** [comment]
The thing is that nothing is executed in autoSearchTasks

**Comment by davestewart** [comment]
What happens if you don't remove the tabs before sending the message?

My hunch is perhaps a newly-opened tab – even though the await has completed – may not yet have run the code inside it, and so `bus` will not yet exist.

Also, is `listElements` defined? Just try sending a message which says "Hello" or something.

Do you know how to use the debugger?

In both page and popup?

In the debugger you can test everything exists and is calling, by setting bus as a `window` property:

```ts
window['bus'] = bus
```

Then in the popup console, run the code manually:

```ts
bus.call('search: showList')
```

**Comment by FJRG2007** [comment]
That's in case the user has a previous tab with that url, it should not affect it, it is supposed to

**Comment by FJRG2007** [comment]
> What happens if you don't remove the tabs before sending the message?
> 
> My hunch is perhaps a newly-opened tab – even though the await has completed – may not yet have run the code inside it, and so `bus` will not yet exist.
> 
> Also, is `listElements` defined? Just try sending a message which says "Hello" or something.
> 
> Do you know how to use the debugger?
> 
> In both page and popup?
> 
> In the debugger you can test everything exists and is calling, by setting bus as a `window` property:
> 
> ```ts
> window['bus'] = bus
> ```
> 
> Then in the popup console, run the code manually:
> 
> ```ts
> bus.call('search: showList')
> ```

![image](https://github.com/davestewart/extension-bus/assets/79384376/ac81b89f-9c9e-471a-bcdb-5ef2b4dc0abb)
But apparently it does nothing

**Comment by davestewart** [comment]
Ok. I suggest running the demos locally and trying to understand the code there 👍

**Comment by FJRG2007** [comment]
I am trying several ways to see if I can do it.

**Comment by davestewart** [comment]
You got it up and running!?

LMK what was not clear in case I need to update the docs 👍

**Comment by FJRG2007** [comment]
The truth is, I haven't got it yet, it's a weird thing because I don't even get an error.

**Comment by davestewart** [comment]
Well if the code is public let me know and I can take a look

**Comment by FJRG2007** [comment]
I'm trying something else, you can see it also in the WXT Discord server help thread.

**Comment by davestewart** [comment]
> The truth is, I haven't got it yet, it's a weird thing because I don't even get an error.

Forgot to mention, you can check the `bus.error` property to see if something failed, and why:

- https://github.com/davestewart/extension-bus#error-handling

**Comment by FJRG2007** [comment]
I will look into it as well
